name: Generate PDF
on:
  workflow_dispatch:

jobs:

  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: lgmorand/github-action-pandoc@main
        with:
          args: "--standalone --output=sample.pdf sample.md"
      - uses: actions/upload-artifact@v4
        with:
          name: "PDF"
          path: sample.pdf

