name: Publish Docker Image
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'version of the container image'
        required: true 
      image:
        description: 'name of the container image'
        required: true 
        default: "lgmorand/github-action-pandoc"
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Docker Hub login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push image to Docker Hub
        run: |
          # retrieve version from input
          VERSION="${{ github.event.inputs.version }}"
          IMAGE_NAME="${{ github.event.inputs.image }}"
          TAG="$IMAGE_NAME:$VERSION"
          echo $TAG
          # Build and tag image
          docker build . --file Dockerfile --tag $IMAGE_NAME --label "org.opencontainers.image.version=$VERSION"
          docker tag $IMAGE_NAME $TAG
          
          docker push $TAG
