name: Publish Docker Image
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'version of the container image'
        required: true 
env:
  IMAGE_NAME: lgmorand/github-action-pandoc
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Docker Hub login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push image to Docker Hub
        run: |
          # Strip git ref prefix from version
          VERSION="${{ github.event.inputs.version }}"

          # Build and tag image
          docker build . --file Dockerfile --tag $IMAGE_NAME --label "org.opencontainers.image.version=$VERSION"
          docker tag $IMAGE_NAME $IMAGE_NAME:$VERSION
          # Tag with the minor version if valid
          MINOR_VERSION=$(echo $VERSION | sed -n "s/^\([0-9]*.[0-9]*\).[0-9]*$/\1/p")
          [[ ${#MINOR_VERSION} -gt 0 ]] && docker tag $IMAGE_NAME $IMAGE_NAME:$MINOR_VERSION
          # Tag with the major version if valid
          MAJOR_VERSION=$(echo $VERSION | sed -n "s/^\([0-9]*\).[0-9]*.[0-9]*$/\1/p")
          [[ ${#MAJOR_VERSION} -gt 0 ]] && docker tag $IMAGE_NAME $IMAGE_NAME:$MAJOR_VERSION
          docker push $IMAGE_NAME
